spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        platform: h2
        initialization-mode: always
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:healthometer;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: healthometer
        password: h34lth0m3t3r
        hikari:
            auto-commit: false
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: none

server:
    port: 8080

swagger:
    enabled: true

logging:
    level:
        org.springframework: ERROR
        it.sogin.aigor: INFO
    pattern:
        console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
        file: "%d %p %c{1.} [%t] %m%n"
    file: healthometer.log


